### ISSUE TITLE
Please add example to fetch locations & reviews w/ service account

### ISSUE THREAD

**Issue by skunkbad** [spotonlive/php-google-my-business#7]
It would be nice if you would provide an example of fetching locations and reviews with a service account. It seems that service account access may be different for GMB, and there is not one complete example in the entire internet to show how to fetch locations and reviews with one. It's important to use a service account because it's server to server communication without a human. I can do something like this, but fails:

```
putenv('GOOGLE_APPLICATION_CREDENTIALS=/service-account.json');
$client = new Google_Client();
$client->useApplicationDefaultCredentials();
$client->addScope('https://www.googleapis.com/auth/plus.business.manage');
$gmb = new Google_Service_MyBusiness( $client );
$accounts = $gmb->accounts->listAccounts()->getAccounts();
$location = $gmb->accounts_locations->listAccountsLocations( $accounts[0]['name'] );
var_dump( $location->getLocations() );
```

Locations are always empty, so can't get locations or reviews that are tied to them. The Google My Business community forum is not helping. Please consider an example or two.

**Comment by sfatfarma** [comment]
Hello,

Using the code example you provided, I can list locations without issues. I think the issue is with your API access credentials. You should contact Google My Business api support and ask them about this (if this is not solved since it was posted).

Regards,
Szabi - CodeRevolution.
https://codecanyon.net/user/coderevolution/portfolio
